name: tezpay
description: A new Flutter application.
version: 0.0.1+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base
  tezart: ^1.0.1
  nb_utils: ^4.4.4
  google_fonts: ^2.1.0
  flutter_keychain: ^2.0.1

  # IMAGES
  card_swiper: ^1.0.2

  # STATE MANAGEMENT
  async_redux: ^12.0.0
  equatable: ^2.0.3

  # WEB TOOLS
  webview_flutter: ^2.0.8

  # UI
  auto_size_text: ^3.0.0-nullsafety.0
  simple_animations: ^3.1.1
  flutter_svg: ^0.22.0
  flutter_slidable: ^0.6.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_staggered_animations: ^1.0.0
  signature: ^4.1.1
  dots_indicator: ^2.0.0
  carousel_slider: ^4.0.0
  animations: ^2.0.1
  # liquid_swipe: ^2.1.0
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_reaction_button: ^1.0.8
  showcaseview: ^1.0.0
  fl_chart: ^0.36.1
  syncfusion_flutter_charts: ^19.1.67

  # NOTIFICATION
  flutter_local_notifications: ^5.0.0+4
  onesignal_flutter: 3.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.6

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/xtz-logo.svg

  fonts:
    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf

